apiVersion: v1
kind: Service
metadata:
  name: whatscrm-api
  namespace: whatscrm
  labels:
    app: whatscrm-api
spec:
  selector:
    app: whatscrm-api
  ports:
    - name: http
      port: 4000
      targetPort: http
