apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whatscrm
  namespace: whatscrm
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
spec:
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: whatscrm-api
                port:
                  number: 4000
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: whatscrm-api
                port:
                  number: 4000
