import { z } from "zod";
import { bearerSecurity, dataResponseSchema, jsonResponse, rawResponse, registry, standardErrorResponses } from "../registry.js";
import {
  analyzeSchema,
  knowledgeSchema,
  searchQuerySchema,
  streamSchema,
  toolCallSchema,
  transcribeSchema,
  voiceReplySchema,
} from "../../routes/assistant.js";

const TAGS = ["AI Assistant"];

registry.registerPath({
  method: "get",
  path: "/api/assistant/overview",
  tags: TAGS,
  summary: "AI assistant provider configuration, capabilities, and recent activity.",
  security: bearerSecurity,
  responses: {
    200: jsonResponse("Assistant overview.", z.unknown()),
    ...standardErrorResponses,
  },
});

registry.registerPath({
  method: "post",
  path: "/api/assistant/analyze",
  tags: TAGS,
  summary: "Run an AI analysis task (full analysis, draft reply, etc.) against a conversation.",
  security: bearerSecurity,
  request: { body: { content: { "application/json": { schema: analyzeSchema } } } },
  responses: {
    200: jsonResponse("Analysis result.", dataResponseSchema),
    ...standardErrorResponses,
  },
});

registry.registerPath({
  method: "post",
  path: "/api/assistant/stream",
  tags: TAGS,
  summary: "Stream an AI analysis task as Server-Sent Events.",
  security: bearerSecurity,
  request: { body: { content: { "application/json": { schema: streamSchema } } } },
  responses: {
    200: rawResponse("Server-Sent Events stream.", "text/event-stream"),
    ...standardErrorResponses,
  },
});

registry.registerPath({
  method: "get",
  path: "/api/assistant/search",
  tags: TAGS,
  summary: "Full-text search across messages and knowledge base entries.",
  security: bearerSecurity,
  request: { query: searchQuerySchema },
  responses: {
    200: jsonResponse("Search results.", z.object({ data: z.object({ messages: z.unknown(), knowledge: z.unknown() }) })),
    ...standardErrorResponses,
  },
});

registry.registerPath({
  method: "post",
  path: "/api/assistant/knowledge",
  tags: TAGS,
  summary: "Add a knowledge base entry the assistant can draw on.",
  security: bearerSecurity,
  request: { body: { content: { "application/json": { schema: knowledgeSchema } } } },
  responses: {
    201: jsonResponse("Created knowledge entry.", dataResponseSchema),
    ...standardErrorResponses,
  },
});

registry.registerPath({
  method: "post",
  path: "/api/assistant/voice/transcribe",
  tags: TAGS,
  summary: "Record a voice transcription against the assistant's activity log.",
  security: bearerSecurity,
  request: { body: { content: { "application/json": { schema: transcribeSchema } } } },
  responses: {
    200: jsonResponse("Transcription record.", dataResponseSchema),
    ...standardErrorResponses,
  },
});

registry.registerPath({
  method: "post",
  path: "/api/assistant/voice/reply",
  tags: TAGS,
  summary: "Record a voice reply generated by the assistant.",
  security: bearerSecurity,
  request: { body: { content: { "application/json": { schema: voiceReplySchema } } } },
  responses: {
    200: jsonResponse("Voice reply record.", dataResponseSchema),
    ...standardErrorResponses,
  },
});

registry.registerPath({
  method: "post",
  path: "/api/assistant/tool-call",
  tags: TAGS,
  summary: "Invoke a named assistant tool (e.g. updateLeadStage) with free-form arguments.",
  security: bearerSecurity,
  request: { body: { content: { "application/json": { schema: toolCallSchema } } } },
  responses: {
    200: jsonResponse("Tool call result.", dataResponseSchema),
    ...standardErrorResponses,
  },
});
